name: Alfajores (DEV) Proxy Upgrades.

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: env $(cat .env) npx hardhat run --network alfajores scripts/upgrade_nashescrow_testnet.ts
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CELOSCAN_API_KEY: ${{ secrets.CELOSCAN_API_KEY }}
